### PR TITLE
Add Dark Theme

### PR DESCRIPTION
**Pull request by Zaurzo**
Adds a dark theme to the Luapad editor:
luapad_dark_theme

The theme can be changed within the Settings panel:
luapad_settings

I also removed a few instances of argument overloading for surface.SetDrawColor calls as it is faster.

### CODE REVIEW

**Comment by wrefgtzweve** [comment]
Im getting a error per frame after opening the luapad menu now
```
[luapad] addons/luapad/lua/luapad/client/luapad_editorpanel.lua:489: attempt to index a nil value
  1. PaintLine - addons/luapad/lua/luapad/client/luapad_editorpanel.lua:489
   2. unknown - addons/luapad/lua/luapad/client/luapad_editorpanel.lua:533 (x274)
```

**Comment by Zaurzo** [comment]
fixed. me when PANEL:Paint() is called before PANEL:Init()

**Comment by wrefgtzweve** [comment]
Still errors

**Comment by Zaurzo** [comment]
Okay, it should be fixed now. It was because a field name was wrong, whoops, lol

**Comment by wrefgtzweve** [comment]
Seems good to go
One last thing, maybe a more specific name for the color palette could be nice, if you used a preexisting dark theme color scheme you could name it after it
I feel like people in the future might make other prs for other dark theme colors so having a name could be nice. If you don't know a specific name thats fine i can just merge it for now

**Comment by Zaurzo** [comment]
> Seems good to go One last thing, maybe a more specific name for the color palette could be nice, if you used a preexisting dark theme color scheme you could name it after it I feel like people in the future might make other prs for other dark theme colors so having a name could be nice. If you don't know a specific name thats fine i can just merge it for now

Really it's supposed to be THE dark theme for it, if you know what I mean. I don't really have a specific name in mind though, so go ahead and merge

**Comment by Zaurzo** [comment]
I added theme base inheritance. That way, people can derive off of the existing themes, so they don't need to copy colors if they want their theme to wants to use a few colors from the dark theme for example.

**Review by wrefgtzweve — APPROVED** [review]

**Pull request merged**
